### ISSUE TITLE
Showing error in netbeans

### ISSUE THREAD

**Issue by vinayakumarr** [ahlashkari/ISCXFlowMeter#1]
When i try to run this with you pcaps, in netbeans it is showing the below error
![untitled](https://cloud.githubusercontent.com/assets/18217467/23825396/2669f0e0-06af-11e7-92c5-6f025c57299e.png)

**Comment by vinayakumarr** [comment]
dependency for jnetpcap is resolved but now it is showing the compilation error for extracting features for ISCX_Botnet

**Comment by ahlashkari** [comment]
Hi,
As you can see in the first red line, you have still dependencies issue. Please follow the issue up and handle the dependencies issue. If you want to run an open source program, at first you need to have all libraries and dependencies there. 
BTW, application is working with all PCAP files and if the flow is not complete it will just jump from it and will go to the next flow. But you can find the number of generated and crashed flows at the end.

**Comment by vinayakumarr** [comment]
I am using CICFlow meter for Botnet dataset (
http://www.unb.ca/cic/research/datasets/botnet.html). The program ran
successfully.

I had 3 PCAP files

ISCX_Botnet-Testing.pcap
ISCX_Botnet-Training.pcap
"testDset-with iscx.pcap"

When i ran program, it generated 3 csv files. Each csv file has 84 features
and a class label and class label contains only benign. But it should
contain

Neris | IRC | 21159 (12%)
Rbot | IRC | 39316 (22%)
Virut | HTTP | 1638 (0.94 %)
NSIS | P2P | 4336 (2.48%)
SMTP Spam | P2P | 11296 (6.48%)
Zeus | P2P | 31 (0.01%)
Zeus control (C & C) | P2P | 20 (0.01%)

Could you please help how to resolve this?

**Comment by ahlashkari** [comment]
?Hi,

The Flowmeter is a CSV / flow generator and you should label your flows. The last column has been generated to help the user to fill up easily (CICFlowMeter is filling all of them by Benign automatically).


Best Regards,
Dr. Arash Habibi Lashkari
Research Associate | R&D Manager
Canadian Institute for Cybersecurity (CIC)
Faculty of Computer Science | University of New Brunswick
550 Windsor Street  | Fredericton, NB, E3B 5A3, Canada
Tel: (506)458-3922  |  A.Habibi.L@unb.ca<mailto:ghorbani@unb.ca>
http://cs.unb.ca/people/alashkar



________________________________

**Comment by vinayakumarr** [comment]
I am not using the custom build in pcaps. I am using your botnet pcaps.

**Comment by ahlashkari** [comment]
Hi,

As I mentioned in the previous text. It is a flow generator and is not a labelling or tagging system.

As you know, for labelling the traffic you need to have your activities schedule and then label the flows based on your specific schedule. For any dataset, if you have the schedule for the actives, then you can label the generated records in the CSV file based on that schedule.

For example, If you have the "Attack A" activity between 8:00 to 9:00 AM from IP1 to IP2 in your dataset, so in the CSV file all records which are from IP1 to IP2 between 8:00 to 9:00 AM should be labeled as" Attack A".

Normally, It is not possible that an application does it automatically, but you can define some script to do it semi-automatically based on your activities schedule if you are familiar with a CSV file format.


Best Regards,
Dr. Arash Habibi Lashkari
Research Associate | R&D Manager
Canadian Institute for Cybersecurity (CIC)
Faculty of Computer Science | University of New Brunswick
550 Windsor Street  | Fredericton, NB, E3B 5A3, Canada
Tel: (506)458-3922  |  A.Habibi.L@unb.ca<mailto:ghorbani@unb.ca>
http://cs.unb.ca/people/alashkar



________________________________

**Comment by ahlashkari** [comment]
Hi,
If you are working and interesting on the security dataset and related analysis, such as network traffic analysis. I am going to present one of our new security data analyzer on this Thursday as a webinar.
Also, I am presenting how we used this analyzer to monitor and detect the Dark web traffic and proposed a very fast detector for just 15s.
Please join me here:
https://www.eventbrite.ca/e/meet-our-cybersecurity-experts-tickets-38246215460’

Finally a free version of the analyzer with the visualization module (Machine learning visualization and traffic profiling) will distribute to the audiences in this webinar.




Best Regards,
Dr. Arash Habibi Lashkari
Research Associate | R&D Manager
Canadian Institute for Cybersecurity (CIC)
Faculty of Computer Science | University of New Brunswick
550 Windsor Street  | Fredericton, NB, E3B 5A3, Canada
Tel: (506)458-3922  |  A.Habibi.L@unb.ca<mailto:ghorbani@unb.ca>
http://cs.unb.ca/people/alashkar



________________________________

**Comment by vinayakumarr** [comment]
I have generated 3 csv files for the botnet pcaps. Is there any code which you can share to label the date. It will be very helpfull

**Comment by ahlashkari** [comment]
Hi,
There is no automatic labelling package. Normally, you need to read your dataset documents and figure our how can label the flows. 

Good luck,
