### ISSUE TITLE
Running through commandline

### ISSUE THREAD

**Issue by vinayakumarr** [ahlashkari/ISCXFlowMeter#2]
It will be very helpful if you give sh commands to run on servers. I have downloaded this and tried in windows machine, it works fine for less size pcaps. For large size, i am getting memory error. I want to run it on on server, where i dont have a GUI. I want to run through  shell script including all dependencies. Could you please tell how to run your program through command line.

**Comment by ahlashkari** [comment]
Hi Vinayakumarr,
As you have the source code in Java, so you can create a jar file in any compiler with all dependencies and run on the command line. For finding the Jar file and the new version of this project with more than 80 traffic features, please check the applications page on our website: http://unb.ca/cic/research/applications.html

**Comment by ahlashkari** [comment]
Hi ,
If you and your friends are working and interesting on the security dataset and related analysis, such as network traffic analysis. I am going to present one of our new security data analyzer and two new datasets on next Tuesday as a free webinar in titled "Dark Web monitoring and detection".

Also, I am presenting two experiments that show how we used this analyzer to monitor and detect the Dark web traffic and proposed a very fast detector for just 15s.

Finally a free version of the analyzer with the easy to use GUI will give as a gift to the attendees in this webinar.

Please join me here:
https://www.eventbrite.ca/e/meet-our-cybersecurity-experts-tickets-39008063167




Best Regards,
Dr. Arash Habibi Lashkari
Research Associate | R&D Manager
Canadian Institute for Cybersecurity (CIC)
Faculty of Computer Science | University of New Brunswick
550 Windsor Street  | Fredericton, NB, E3B 5A3, Canada
Tel: (506)458-3922  |  A.Habibi.L@unb.ca<mailto:ghorbani@unb.ca>
http://cs.unb.ca/people/alashkar



________________________________
